type Query {
  node(id: ID!, revision: ID): NodeUnion
  paragraph(id: ID!, revision: ID): ParagraphUnion
  term(id: ID!, revision: ID): TermUnion
  menu(name: MenuAvailable!): Menu
  info: SchemaInformation!
  nodeCouncilMembers(after: Cursor, before: Cursor, first: Int, last: Int, reverse: Boolean, sortKey: ConnectionSortKeys): NodeCouncilMemberConnection!
  nodeDepartments(after: Cursor, before: Cursor, first: Int, last: Int, reverse: Boolean, sortKey: ConnectionSortKeys): NodeDepartmentConnection!
  nodeEvents(after: Cursor, before: Cursor, first: Int, last: Int, reverse: Boolean, sortKey: ConnectionSortKeys): NodeEventConnection!
  nodeHomepages(after: Cursor, before: Cursor, first: Int, last: Int, reverse: Boolean, sortKey: ConnectionSortKeys): NodeHomepageConnection!
  nodeNewsItems(after: Cursor, before: Cursor, first: Int, last: Int, reverse: Boolean, sortKey: ConnectionSortKeys): NodeNewsConnection!
  nodePages(after: Cursor, before: Cursor, first: Int, last: Int, reverse: Boolean, sortKey: ConnectionSortKeys): NodePageConnection!
  nodeServices(after: Cursor, before: Cursor, first: Int, last: Int, reverse: Boolean, sortKey: ConnectionSortKeys): NodeServiceConnection!
  paragraphStatItems(after: Cursor, before: Cursor, first: Int, last: Int, reverse: Boolean, sortKey: ConnectionSortKeys): ParagraphStatItemConnection!
  termTags(after: Cursor, before: Cursor, first: Int, last: Int, reverse: Boolean, sortKey: ConnectionSortKeys): TermTagConnection!
  preview(id: ID!, token: String, langcode: String): NodeUnion
  route(path: String!, revision: ID): RouteUnion
}

union NodeUnion = NodeCouncilMember | NodeDepartment | NodeEvent | NodeHomepage | NodeNews | NodePage | NodeService

type NodeCouncilMember implements NodeInterface & EdgeNode {
  id: ID!
  uuid: ID!
  body: TextSummary
  changed: DateTime!
  created: DateTime!
  district: String
  email: String
  langcode: Language!
  path: String
  phone: String
  photo: Image
  position: String
  promote: Boolean!
  status: Boolean!
  sticky: Boolean!
  termDates: String
  title: String!
}

interface NodeInterface {
  id: ID!
  uuid: ID!
  changed: DateTime!
  created: DateTime!
  langcode: Language!
  path: String
  promote: Boolean!
  status: Boolean!
  sticky: Boolean!
  title: String!
}

type DateTime {
  timestamp: Timestamp!
  timezone: TimeZone!
  offset: UtcOffset!
  time: Time!
}

type Language {
  id: ID
  name: String
  direction: String
}

interface EdgeNode {
  id: ID!
}

type TextSummary {
  value: String
  processed: Html
  format: String
  summary: Html
}

type Image {
  url: String!
  width: Int!
  height: Int!
  alt: String
  title: String
  size: Int!
  mime: String
  variations(styles: [ImageStyleAvailable]): [ImageStyleDerivative!]
}

enum ImageStyleAvailable {
  LARGE
  MEDIA_LIBRARY
  MEDIUM
  THUMBNAIL
  WIDE
}

type ImageStyleDerivative {
  name: String!
  url: String!
  width: Int!
  height: Int!
}

type NodeDepartment implements NodeInterface & EdgeNode {
  id: ID!
  uuid: ID!
  body: TextSummary
  changed: DateTime!
  created: DateTime!
  departmentCategory: [TermUnion!]
  email: String
  hours: String
  image: Image
  langcode: Language!
  location: String
  path: String
  phone: String
  promote: Boolean!
  status: Boolean!
  sticky: Boolean!
  title: String!
}

union TermUnion = TermDepartment | TermEventCategory | TermNewsCategory | TermServiceCategory | TermTag

type TermDepartment implements TermInterface {
  id: ID!
  uuid: ID!
  changed: DateTime!
  description: Text!
  langcode: Language!
  name: String!
  parent: TermUnion
  path: String
  status: Boolean!
  weight: Int!
}

interface TermInterface {
  id: ID!
  uuid: ID!
  changed: DateTime!
  description: Text!
  langcode: Language!
  name: String!
  parent: TermUnion
  path: String
  status: Boolean!
  weight: Int!
}

type Text {
  value: String
  processed: Html
  format: String
}

type TermEventCategory implements TermInterface {
  id: ID!
  uuid: ID!
  changed: DateTime!
  description: Text!
  langcode: Language!
  name: String!
  parent: TermUnion
  path: String
  status: Boolean!
  weight: Int!
}

type TermNewsCategory implements TermInterface {
  id: ID!
  uuid: ID!
  changed: DateTime!
  description: Text!
  langcode: Language!
  name: String!
  parent: TermUnion
  path: String
  status: Boolean!
  weight: Int!
}

type TermServiceCategory implements TermInterface {
  id: ID!
  uuid: ID!
  changed: DateTime!
  description: Text!
  langcode: Language!
  name: String!
  parent: TermUnion
  path: String
  status: Boolean!
  weight: Int!
}

type TermTag implements TermInterface & EdgeNode {
  id: ID!
  uuid: ID!
  changed: DateTime!
  description: Text!
  langcode: Language!
  name: String!
  parent: TermUnion
  path: String
  status: Boolean!
  weight: Int!
}

type NodeEvent implements NodeInterface & EdgeNode {
  id: ID!
  uuid: ID!
  body: TextSummary
  changed: DateTime!
  created: DateTime!
  endDate: DateTime
  eventCategory: [TermUnion!]
  eventDate: DateTime
  image: Image
  langcode: Language!
  location: String
  openToPublic: Boolean
  path: String
  promote: Boolean!
  status: Boolean!
  sticky: Boolean!
  title: String!
}

type NodeHomepage implements NodeInterface & EdgeNode {
  id: ID!
  uuid: ID!
  changed: DateTime!
  created: DateTime!
  ctaDescription: Text
  ctaPrimary: String
  ctaSecondary: String
  ctaTitle: String
  featuredItemsTitle: String
  heroDescription: Text
  heroSubtitle: String
  heroTitle: String
  langcode: Language!
  path: String
  promote: Boolean!
  statsItems: [ParagraphUnion!]
  status: Boolean!
  sticky: Boolean!
  title: String!
}

union ParagraphUnion = ParagraphStatItem

type ParagraphStatItem implements ParagraphInterface & EdgeNode {
  id: ID!
  uuid: ID!
  created: DateTime!
  label: String
  langcode: Language!
  number: String
  status: Boolean!
}

interface ParagraphInterface {
  id: ID!
  uuid: ID!
  created: DateTime!
  langcode: Language!
  status: Boolean!
}

type NodeNews implements NodeInterface & EdgeNode {
  id: ID!
  uuid: ID!
  body: TextSummary
  category: [TermUnion!]
  changed: DateTime!
  created: DateTime!
  featured: Boolean
  image: Image
  langcode: Language!
  path: String
  promote: Boolean!
  status: Boolean!
  sticky: Boolean!
  title: String!
}

type NodePage implements NodeInterface & EdgeNode {
  id: ID!
  uuid: ID!
  body: TextSummary
  changed: DateTime!
  created: DateTime!
  langcode: Language!
  path: String
  promote: Boolean!
  status: Boolean!
  sticky: Boolean!
  title: String!
}

type NodeService implements NodeInterface & EdgeNode {
  id: ID!
  uuid: ID!
  body: TextSummary
  changed: DateTime!
  contactPhone: String
  created: DateTime!
  department: [TermUnion!]
  eligibility: String
  image: Image
  langcode: Language!
  path: String
  promote: Boolean!
  serviceCategory: [TermUnion!]
  status: Boolean!
  sticky: Boolean!
  title: String!
}

enum MenuAvailable {
  MAIN
}

type Menu implements MenuInterface {
  id: ID!
  uuid: ID!
  items: [MenuItem!]!
  name: String!
}

interface MenuInterface {
  id: ID!
  uuid: ID!
  items: [MenuItem!]!
  name: String!
}

type MenuItem {
  id: ID!
  title: String!
  description: String
  url: String
  langcode: Language!
  internal: Boolean!
  expanded: Boolean!
  attributes: MenuItemAttributes!
  children: [MenuItem!]!
  route: RouteUnion
}

type MenuItemAttributes {
  class: String
}

union RouteUnion = RouteInternal | RouteExternal

type RouteInternal implements Route {
  url: String!
  internal: Boolean!
  breadcrumbs: [Link!]
  entity: RouteEntityUnion
}

interface Route {
  url: String!
  internal: Boolean!
}

type Link {
  title: String
  url: String
  internal: Boolean!
}

union RouteEntityUnion = NodeCouncilMember | NodeDepartment | NodeEvent | NodeHomepage | NodeNews | NodePage | NodeService

type RouteExternal implements Route {
  url: String!
  internal: Boolean!
}

type SchemaInformation {
  description: String
  home: String
  name: String
  slogan: String
  version: String
}

enum ConnectionSortKeys {
  CREATED_AT
  UPDATED_AT
  TITLE
  STICKY
  PROMOTED
  WEIGHT
}

type NodeCouncilMemberConnection implements Connection {
  edges: [NodeCouncilMemberEdge!]!
  nodes: [NodeCouncilMember!]!
  pageInfo: ConnectionPageInfo!
}

interface Connection {
  edges: [Edge!]!
  nodes: [EdgeNode!]!
  pageInfo: ConnectionPageInfo!
}

interface Edge {
  cursor: Cursor!
  node: EdgeNode!
}

type ConnectionPageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: Cursor
  endCursor: Cursor
}

type NodeCouncilMemberEdge implements Edge {
  cursor: Cursor!
  node: NodeCouncilMember!
}

type NodeDepartmentConnection implements Connection {
  edges: [NodeDepartmentEdge!]!
  nodes: [NodeDepartment!]!
  pageInfo: ConnectionPageInfo!
}

type NodeDepartmentEdge implements Edge {
  cursor: Cursor!
  node: NodeDepartment!
}

type NodeEventConnection implements Connection {
  edges: [NodeEventEdge!]!
  nodes: [NodeEvent!]!
  pageInfo: ConnectionPageInfo!
}

type NodeEventEdge implements Edge {
  cursor: Cursor!
  node: NodeEvent!
}

type NodeHomepageConnection implements Connection {
  edges: [NodeHomepageEdge!]!
  nodes: [NodeHomepage!]!
  pageInfo: ConnectionPageInfo!
}

type NodeHomepageEdge implements Edge {
  cursor: Cursor!
  node: NodeHomepage!
}

type NodeNewsConnection implements Connection {
  edges: [NodeNewsEdge!]!
  nodes: [NodeNews!]!
  pageInfo: ConnectionPageInfo!
}

type NodeNewsEdge implements Edge {
  cursor: Cursor!
  node: NodeNews!
}

type NodePageConnection implements Connection {
  edges: [NodePageEdge!]!
  nodes: [NodePage!]!
  pageInfo: ConnectionPageInfo!
}

type NodePageEdge implements Edge {
  cursor: Cursor!
  node: NodePage!
}

type NodeServiceConnection implements Connection {
  edges: [NodeServiceEdge!]!
  nodes: [NodeService!]!
  pageInfo: ConnectionPageInfo!
}

type NodeServiceEdge implements Edge {
  cursor: Cursor!
  node: NodeService!
}

type ParagraphStatItemConnection implements Connection {
  edges: [ParagraphStatItemEdge!]!
  nodes: [ParagraphStatItem!]!
  pageInfo: ConnectionPageInfo!
}

type ParagraphStatItemEdge implements Edge {
  cursor: Cursor!
  node: ParagraphStatItem!
}

type TermTagConnection implements Connection {
  edges: [TermTagEdge!]!
  nodes: [TermTag!]!
  pageInfo: ConnectionPageInfo!
}

type TermTagEdge implements Edge {
  cursor: Cursor!
  node: TermTag!
}

type Mutation {
  _: Boolean!
}

type Subscription {
  _: Boolean!
}

type DateRange {
  start: DateTime
  end: DateTime
}

type File {
  name: String
  url: String!
  size: Int!
  mime: String
  description: String
}

type ImageStyle implements ImageStyleInterface {
  id: ID!
  uuid: ID!
}

interface ImageStyleInterface {
  id: ID!
  uuid: ID!
}

union ImageStyleUnion = ImageStyle

input KeyValueInput {
  key: String!
  value: String
}

union MenuUnion = Menu

enum SortDirection {
  ASC
  DESC
}

type UnsupportedType {
  unsupported: Boolean
}
